/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as TabsIndexRouteImport } from './routes/_tabs.index'
import { Route as TabsSettingsRouteImport } from './routes/_tabs.settings'
import { Route as TabsAboutRouteImport } from './routes/_tabs.about'

const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsIndexRoute = TabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsRoute,
} as any)
const TabsSettingsRoute = TabsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAboutRoute = TabsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => TabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TabsIndexRoute
  '/about': typeof TabsAboutRoute
  '/settings': typeof TabsSettingsRoute
}
export interface FileRoutesByTo {
  '/about': typeof TabsAboutRoute
  '/settings': typeof TabsSettingsRoute
  '/': typeof TabsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_tabs': typeof TabsRouteWithChildren
  '/_tabs/about': typeof TabsAboutRoute
  '/_tabs/settings': typeof TabsSettingsRoute
  '/_tabs/': typeof TabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/settings' | '/'
  id: '__root__' | '/_tabs' | '/_tabs/about' | '/_tabs/settings' | '/_tabs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TabsRoute: typeof TabsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/': {
      id: '/_tabs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TabsIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/settings': {
      id: '/_tabs/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof TabsSettingsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/about': {
      id: '/_tabs/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof TabsAboutRouteImport
      parentRoute: typeof TabsRoute
    }
  }
}

interface TabsRouteChildren {
  TabsAboutRoute: typeof TabsAboutRoute
  TabsSettingsRoute: typeof TabsSettingsRoute
  TabsIndexRoute: typeof TabsIndexRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsAboutRoute: TabsAboutRoute,
  TabsSettingsRoute: TabsSettingsRoute,
  TabsIndexRoute: TabsIndexRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  TabsRoute: TabsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
